version: "3.9"

services:

  postgres:
    image: postgres:16

    container_name: smartmoney-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: smartmoney
      POSTGRES_DB: smartmoney

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: