"""Add discovery jobs table

Revision ID: 43d107b1734a
Revises: b2359416fd65
Create Date: 2026-07-03 16:00:55.614233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d107b1734a'
down_revision: Union[str, Sequence[str], None] = 'b2359416fd65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('seed_wallet', sa.String(length=64), nullable=False),
    sa.Column('wallets_found', sa.Integer(), nullable=False),
    sa.Column('wallets_processed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_jobs_id'), 'discovery_jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovery_jobs_id'), table_name='discovery_jobs')
    op.drop_table('discovery_jobs')
    # ### end Alembic commands ###
