"""Add discovered wallets table

Revision ID: 5d4afe80ab1f
Revises: a4ada377ff23
Create Date: 2026-07-03 15:19:12.220588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d4afe80ab1f'
down_revision: Union[str, Sequence[str], None] = 'a4ada377ff23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('discovered_from_token', sa.String(length=64), nullable=True),
    sa.Column('smart_score', sa.Float(), nullable=False),
    sa.Column('roi_percent', sa.Float(), nullable=False),
    sa.Column('win_rate_percent', sa.Float(), nullable=False),
    sa.Column('profit_loss_sol', sa.Float(), nullable=False),
    sa.Column('reliable_positions', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovered_wallets_id'), 'discovered_wallets', ['id'], unique=False)
    op.create_index(op.f('ix_discovered_wallets_wallet_address'), 'discovered_wallets', ['wallet_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovered_wallets_wallet_address'), table_name='discovered_wallets')
    op.drop_index(op.f('ix_discovered_wallets_id'), table_name='discovered_wallets')
    op.drop_table('discovered_wallets')
    # ### end Alembic commands ###
