"""Update trade model for parsed swaps

Revision ID: a4ada377ff23
Revises: f073b65a10cf
Create Date: 2026-07-02 16:25:26.559925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4ada377ff23'
down_revision: Union[str, Sequence[str], None] = 'f073b65a10cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('signature', sa.String(length=128), nullable=False))
    op.add_column('trades', sa.Column('wallet_address', sa.String(length=64), nullable=False))
    op.add_column('trades', sa.Column('side', sa.String(length=20), nullable=False))
    op.add_column('trades', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('trades', sa.Column('token_mint', sa.String(length=64), nullable=True))
    op.add_column('trades', sa.Column('token_amount', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('sol_amount', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('fee', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('success', sa.Boolean(), nullable=False))
    op.add_column('trades', sa.Column('block_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trades', sa.Column('raw_json', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_trades_token_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_wallet_id'), table_name='trades')
    op.create_index(op.f('ix_trades_signature'), 'trades', ['signature'], unique=True)
    op.create_index(op.f('ix_trades_wallet_address'), 'trades', ['wallet_address'], unique=False)
    op.drop_constraint(op.f('trades_wallet_id_fkey'), 'trades', type_='foreignkey')
    op.drop_constraint(op.f('trades_token_id_fkey'), 'trades', type_='foreignkey')
    op.drop_column('trades', 'token_id')
    op.drop_column('trades', 'price')
    op.drop_column('trades', 'wallet_id')
    op.drop_column('trades', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('trades', sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('trades', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('trades', sa.Column('token_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('trades_token_id_fkey'), 'trades', 'tokens', ['token_id'], ['id'])
    op.create_foreign_key(op.f('trades_wallet_id_fkey'), 'trades', 'wallets', ['wallet_id'], ['id'])
    op.drop_index(op.f('ix_trades_wallet_address'), table_name='trades')
    op.drop_index(op.f('ix_trades_signature'), table_name='trades')
    op.create_index(op.f('ix_trades_wallet_id'), 'trades', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_trades_token_id'), 'trades', ['token_id'], unique=False)
    op.drop_column('trades', 'raw_json')
    op.drop_column('trades', 'block_time')
    op.drop_column('trades', 'success')
    op.drop_column('trades', 'fee')
    op.drop_column('trades', 'sol_amount')
    op.drop_column('trades', 'token_amount')
    op.drop_column('trades', 'token_mint')
    op.drop_column('trades', 'source')
    op.drop_column('trades', 'side')
    op.drop_column('trades', 'wallet_address')
    op.drop_column('trades', 'signature')
    # ### end Alembic commands ###
