"""Add wallet last sync

Revision ID: b2359416fd65
Revises: 5d4afe80ab1f
Create Date: 2026-07-03 15:45:55.237403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2359416fd65'
down_revision: Union[str, Sequence[str], None] = '5d4afe80ab1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'last_sync')
    # ### end Alembic commands ###
